[package]
authors = ["Tim Marinin <mt@marinin.xyz>"]
name = "rust-gist"
version = "0.1.0"
license = "MIT"
description = "Yet another Gist client"

[dependencies]
docopt = "0.8.1"
reqwest = "0.8.0"
serde = "1.0.15"
serde_derive = "1.0.15"
serde_json = "1.0.3"
